spring:
  application:
    name: PASSBOOK-GATEWAY
  datasource:
    password: ok
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/austinhub?serverTimezone=America/Chicago&useSSL=false
    username: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: austinhub
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  devtools:
    livereload:
      enabled: true

support:
  email: yunchuwang6@gmail.com
  
server:
  port: 9001

hibernate:
  globally_quoted_identifiers: true

#logging:
#  level:
#    org:
#      hibernate:
#        type: trace